# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bd8228c4a733b9ec89d825d951e889dd7b00876d9d102475efd73dba847a8fd13dd8a51301d19ac91eba0bc5ef8a570783aaea2b6e2f930750256cb6cb1e75e

test:
  secret_key_base: ac9b0d03071e87c94b09ea9149efca387a8f62e3e0aa477095758bf77c17cd0d8b94cfcac9ab91ae4d195cde6c5570cf5f52a3804df76dbd87f5d46def521033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
